server.port=8081
spring.application.name=alert-service
spring.threads.virtual.enabled=true

# Configurables
climalert.target-location=Buenos Aires
climalert.recipients=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

# Correo
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=usuario
spring.mail.password=contraseña